"""State engine: the single source of truth for transport state.

Every controller (deck protocol, REST API, web UI and scheduler later) is a
client of this engine, so they can never disagree about what is on air.

The player is VLC, one process per clip, driven over its RC socket. The
control protocol never waits on the player: every player call has a timeout,
the command lock is never held indefinitely, and the watchdog runs outside it.
"""
import asyncio
import contextlib
import logging
import time

from .player import Mpv, PlayerError, PlayerTimeout

log = logging.getLogger(__name__)


class ClipNotFound(Exception):
    pass


class PlayerUnavailable(Exception):
    """The player is wedged or restarting - the command cannot be honoured."""


class Engine:
    def __init__(self, cfg, library, player=None):
        self.cfg = cfg
        self.library = library
        self.player = player or Mpv(cfg)
        self.status = "stopped"          # "stopped" or "play"
        self.clip_id = None
        self.speed = 100
        self.loop = False
        self.single_clip = False
        self.position = 0.0
        self.started_at = time.monotonic()
        self.player_state = "ok"         # ok | stalled | restarting
        self._gen = 0
        self._still_timer = None
        self._listeners = []
        self._tasks = set()
        self._lock = asyncio.Lock()
        self._restart_lock = asyncio.Lock()
        self._closing = False
        self._poller = None
        self._watchdog = None
        self._probe_failures = 0
        self._last_pos = 0.0
        self._last_pos_time = time.monotonic()
        self._grace_until = 0.0
        self._restarts = 0               # consecutive failed restarts
        self._last_restart = 0.0

    # ----- lifecycle -------------------------------------------------------

    async def start(self):
        await self.player.start()
        if self.library.clips:
            await self.goto_clip(self.default_clip_id() or 1)
            await self.play()            # the default slide goes to air at boot
        else:
            log.warning("No clips in %s - showing black", self.cfg.media_dir)
            await self.show_blank()
        self._poller = asyncio.create_task(self._poll())
        self._watchdog = asyncio.create_task(self._watch())

    async def show_blank(self):
        """Put black on the output.

        With nothing playing the compositor-less display shows the Linux
        console, which at a repeater site would go out on air. Black is
        generated by the player itself, so it needs no file on disk.
        """
        try:
            await self.player.load(self.cfg.blank_source, still=True,
                                   repeat=True, play=True)
            self.clip_id, self.status = None, "play"
            self._notify()
        except PlayerError:
            log.exception("Could not show black")

    async def close(self):
        self._closing = True
        self._cancel_still_timer()
        for task in (self._poller, self._watchdog):
            if task:
                task.cancel()
        await self.player.close()

    # ----- listeners -------------------------------------------------------

    def add_listener(self, callback):
        self._listeners.append(callback)

    def notify_library_changed(self):
        if self.clip_id and self.clip_id > len(self.library.clips):
            self.clip_id = len(self.library.clips) or None
        if not self.library.clips:
            self._spawn(self.show_blank())
        self._notify()

    def _notify(self):
        for cb in self._listeners:
            try:
                cb()
            except Exception:
                log.exception("Listener failed")

    def _spawn(self, coro):
        task = asyncio.create_task(coro)
        self._tasks.add(task)
        task.add_done_callback(self._tasks.discard)

    @contextlib.asynccontextmanager
    async def _guard(self, timeout=3.0):
        """Take the command lock, or give up quickly rather than hang a client."""
        try:
            await asyncio.wait_for(self._lock.acquire(), timeout)
        except asyncio.TimeoutError:
            raise PlayerUnavailable("player busy")
        try:
            yield
        finally:
            self._lock.release()

    # ----- transport commands ---------------------------------------------

    async def goto_clip(self, clip_id):
        async with self._guard():
            await self._load(clip_id)
            self._notify()

    async def seek_clip_start(self):
        async with self._guard():
            await self.player.seek(0)
            self.position = 0.0
            self._notify()

    async def seek_clip_end(self):
        async with self._guard():
            clip = self.library.get(self.clip_id)
            if clip and clip.duration > 2:
                await self.player.seek(int(clip.duration) - 1)
                self.position = clip.duration - 1
            self._notify()

    async def play(self, speed=100, loop=None, single_clip=None):
        async with self._guard():
            if self.clip_id is None:
                if not self.library.clips:
                    raise ClipNotFound("no clips")
                await self._load(self.default_clip_id() or 1)
            reload_needed = False
            if loop is not None and loop != self.loop:
                self.loop, reload_needed = loop, True
            if single_clip is not None and single_clip != self.single_clip:
                self.single_clip, reload_needed = single_clip, True
            self.speed = speed
            if reload_needed:
                # VLC decides repeat at launch, so a loop change means a reload
                await self._load(self.clip_id, resume=self.position)
            if speed != 100:
                with contextlib.suppress(PlayerError):
                    await self.player.rc(f"rate {speed / 100:.2f}", expect_reply=False)
            await self.player.play()
            self.status = "play"
            self._arm_still_timer(self.library.get(self.clip_id))
            self._mark_progress()
            self._notify()

    async def stop(self):
        async with self._guard():
            self._cancel_still_timer()
            await self.player.pause()        # holds the frame, HyperDeck style
            self.status = "stopped"
            self._notify()

    async def set_flags(self, loop=None, single_clip=None):
        """Change loop / single clip without disturbing playback."""
        async with self._guard():
            changed = False
            if loop is not None and loop != self.loop:
                self.loop, changed = loop, True
            if single_clip is not None and single_clip != self.single_clip:
                self.single_clip, changed = single_clip, True
            if changed and self.clip_id and self.status == "play":
                await self._load(self.clip_id, resume=self.position)
                await self.player.play()
            self._notify()

    # ----- internals (call with the lock held) -----------------------------

    def _repeat_wanted(self, clip):
        """Should VLC repeat this clip by itself?"""
        if clip is None:
            return False
        if self.single_clip and self.loop:
            return True
        return clip.behaviour == "loop"

    async def _load(self, clip_id, resume=0.0, play=False):
        clip = self.library.get(clip_id)
        if clip is None:
            raise ClipNotFound(clip_id)
        self._cancel_still_timer()
        self._gen += 1
        await self.player.load(clip.path, still=clip.kind == "still",
                               repeat=self._repeat_wanted(clip), play=play)
        # a clip needs a moment to start reporting; don't call that a stall
        self._grace_until = time.monotonic() + self.cfg.start_grace
        if resume > 1 and clip.kind == "video":
            with contextlib.suppress(PlayerError):
                await self.player.seek(int(resume))
        self.clip_id = clip_id
        self.status = "play" if play else "stopped"
        self.position = resume if resume > 1 else 0.0
        self._mark_progress()
        log.info("Cued clip %d: %s (%s %s)", clip.id, clip.name, clip.kind, clip.codec)

    def _arm_still_timer(self, clip):
        self._cancel_still_timer()
        if clip and clip.kind == "still" and not self.single_clip \
                and clip.behaviour != "loop":
            gen = self._gen
            self._still_timer = asyncio.get_running_loop().call_later(
                max(clip.duration, 1.0), lambda: self._spawn(self._advance(gen)))

    def _cancel_still_timer(self):
        if self._still_timer:
            self._still_timer.cancel()
            self._still_timer = None

    def _mark_progress(self):
        self._last_pos = self.position
        self._last_pos_time = time.monotonic()

    async def _advance(self, gen):
        """Current clip finished: move on according to its behaviour."""
        try:
            async with self._guard():
                if gen != self._gen or self.status != "play":
                    return
                clip = self.library.get(self.clip_id)
                if self.single_clip:
                    self.status = "stopped"      # controller asked for one clip
                    self._notify()
                    return
                behaviour = clip.behaviour if clip else "auto"
                if behaviour == "loop":
                    nxt = self.clip_id
                elif behaviour == "hold":
                    self.status = "stopped"      # hold the last frame
                    self._notify()
                    return
                else:
                    nxt = self.clip_id + 1
                    if nxt > len(self.library.clips):
                        fallback = self.default_clip_id()
                        if fallback:
                            nxt = fallback
                        elif self.loop:
                            nxt = 1
                        else:
                            self.status = "stopped"
                            self._notify()
                            return
                await self._load(nxt)
                await self.player.play()
                self.status = "play"
                self._arm_still_timer(self.library.get(nxt))
                self._notify()
        except (PlayerError, ClipNotFound, PlayerUnavailable):
            log.exception("Advance failed")

    # ----- position polling and watchdog -----------------------------------

    async def _poll(self):
        """Track position and notice when a clip ends. Never takes the lock."""
        while not self._closing:
            await asyncio.sleep(self.cfg.poll_interval)
            if self._restart_lock.locked() or self.player.proc is None:
                continue
            try:
                if self.status == "play":
                    self.position = await self.player.get_time()
                    if await self.player.at_end():
                        self._spawn(self._advance(self._gen))
            except PlayerError:
                pass          # the watchdog deals with a sick player

    async def _watch(self):
        """Prove the player is answering, and that playback is progressing."""
        while not self._closing:
            await asyncio.sleep(self.cfg.watchdog_interval)
            if self._closing or self._restart_lock.locked():
                continue
            if time.monotonic() < self._grace_until or self.player.proc is None:
                continue
            try:
                await self.player.is_alive()
                self._probe_failures = 0
            except PlayerError as exc:
                self._probe_failures += 1
                log.warning("Player probe failed (%d): %s", self._probe_failures, exc)
                if self._probe_failures >= 2:
                    self.player_state = "stalled"
                    self._notify()
                    await self._restart_player("player stopped answering")
                continue
            clip = self.library.get(self.clip_id)
            playing_video = self.status == "play" and clip and clip.kind == "video"
            if playing_video:
                if abs(self.position - self._last_pos) > 0.05:
                    self._mark_progress()
                    self._restarts = 0          # healthy again
                elif time.monotonic() - self._last_pos_time > self.cfg.stall_timeout:
                    log.error("Playback stalled at %.1f s", self.position)
                    self.player_state = "stalled"
                    self._notify()
                    await self._restart_player("playback stalled")
            else:
                self._mark_progress()

    async def _restart_player(self, reason):
        """Rebuild the player and put the transport back where it was."""
        if self._restart_lock.locked():
            return
        now = time.monotonic()
        if now - self._last_restart < self.cfg.restart_backoff * max(self._restarts, 1):
            return                               # too soon - let it settle
        self._last_restart = now
        async with self._restart_lock:
            self._restarts += 1
            if self._restarts > self.cfg.max_restarts:
                clip = self.library.get(self.clip_id)
                name = clip.name if clip else "?"
                log.error("Player failed %d times on %s - falling back to the "
                          "default slide", self._restarts, name)
                fallback = self.default_clip_id()
                if fallback and fallback != self.clip_id:
                    self._restarts = 0
                    self.clip_id = fallback      # try the known-good slide instead
                else:
                    self.player_state = "stalled"
                    self._notify()
                    return
            log.error("Restarting player: %s", reason)
            self.player_state = "restarting"
            self._notify()
            want_clip, want_pos, want_status = self.clip_id, self.position, self.status
            self._cancel_still_timer()
            try:
                await self.player.kill()
                await asyncio.sleep(1)
                await self.player.start()
            except Exception:
                log.exception("Player restart failed")
                self.player_state = "stalled"
                self._notify()
                return
            try:
                async with self._guard(timeout=10):
                    if want_clip and not self.library.get(want_clip):
                        want_clip = self.default_clip_id()
                        want_pos, want_status = 0.0, "play"
                        log.warning("Previous clip is gone - using the default slide")
                    if want_clip:
                        await self._load(want_clip, resume=want_pos)
                        if want_status == "play":
                            await self.player.play()
                            self.status = "play"
                            self._arm_still_timer(self.library.get(want_clip))
                    self.player_state = "ok"
                    self._probe_failures = 0
                    self._mark_progress()
                    self._grace_until = time.monotonic() + max(
                        5.0, self.cfg.stall_timeout + self.cfg.watchdog_interval)
                    self._notify()
                log.info("Player restarted and resumed")
            except (PlayerError, ClipNotFound, PlayerUnavailable):
                log.exception("Could not restore the transport after restart")
                self.player_state = "stalled"
                self._notify()

    # ----- helpers ---------------------------------------------------------

    def default_clip_id(self):
        """The deck's default slide: booted to, returned to, fallen back to."""
        want = str(self.cfg.default_clip).strip()
        if not want:
            return None
        if want.isdigit():
            return int(want) if self.library.get(int(want)) else None
        for c in self.library.clips:
            if c.name == want or c.path.name == want:
                return c.id
        log.warning("default_clip %r not found in the library", want)
        return None

    def timecode(self, seconds=None):
        fps = self.cfg.timecode_fps
        frames = int(round((self.position if seconds is None else seconds) * fps))
        ff = frames % fps
        s = frames // fps
        return f"{s // 3600:02d}:{s // 60 % 60:02d}:{s % 60:02d}:{ff:02d}"

    def transport_info(self):
        tc = self.timecode()
        info = {
            "status": self.status,
            "speed": str(self.speed if self.status == "play" else 0),
            "slot id": "1",
            "clip id": str(self.clip_id) if self.clip_id else "none",
            "single clip": str(self.single_clip).lower(),
            "display timecode": tc,
            "timecode": tc,
            "video format": self.cfg.video_format,
            "loop": str(self.loop).lower(),
        }
        if self.cfg.report_health:
            info["player"] = self.player_state
        return info

    async def player_health(self):
        """Decoder and presentation counters; both zero means all is well."""
        try:
            return await self.player.health()
        except PlayerError:
            return {"decoderDrops": None, "lateFrames": None}

    def uptime(self):
        return int(time.monotonic() - self.started_at)
